apt-get -y remove php-cli
apt-get -y remove apache2
apt-get -y remove apache2-utils
apt-get -y remove bind9
apt-get -y remove courier-authdaemon
apt-get -y remove courier-authlib-mysql
apt-get -y remove courier-imap
apt-get -y remove courier-imap-ssl
apt-get -y remove courier-pop
apt-get -y remove courier-pop-ssl
apt-get -y remove libapache-mod-ssl
apt-get -y remove libpam-mysql
apt-get -y remove libsasl2
apt-get -y remove libsasl2-2
apt-get -y remove libsasl2-modules
apt-get -y remove libsasl2-modules-sql
apt-get -y remove mariadb-client
apt-get -y remove mariadb-server
apt-get -y remove php
apt-get -y remove php5
apt-get -y remove php5-cli
apt-get -y remove php5-gd
apt-get -y remove php5-mysql
apt-get -y remove php5-mysqlnd
apt-get -y remove php-cli
apt-get -y remove phpmyadmin
apt-get -y remove php-mysqlnd
apt-get -y remove pop-before-smtp
apt-get -y remove postfix
apt-get -y remove postfix-mysql
apt-get -y remove python-cherrypy3
apt-get -y remove python-mysqldb
apt-get -y remove roundcube
apt-get -y remove roundcube-mysql
apt-get -y remove roundcube-plugins
apt-get -y remove roundcube-plugins-extra
apt-get -y remove sasl2-bin
apt-get -y remove unrar
apt-get -y remove unzip
apt-get -y remove zip

apt -y remove  apache2 apache2-bin apache2-utils libapache2-mod-php5 libaprutil1-ldap libldap-2.4-2 libsasl2-2 libsasl2-modules
apt -y remove  php5-mysql roundcube-sqlite3 sqlite3
